trigger:
  - develop

pool:
  vmImage: ubuntu-latest
steps:
  - checkout: self
    submodules: true
  - task: Docker@2
    inputs:
      containerRegistry: "ckan510"
      repository: "ckan"
      tags: base
      command: "build"
      Dockerfile: "ckan-build/ckan/Dockerfile"
  - task: Docker@2
    inputs:
      containerRegistry: "ckan510"
      repository: "ckan"
      command: "build"
      Dockerfile: "**/ckan-build/ckan-service/Dockerfile"
      arguments: "--build-arg baseImage=$(CKAN_BASE_IMAGE)"
      buildContext: $(Build.Repository.LocalPath)
  - task: Docker@2
    inputs:
      containerRegistry: "ckan510"
      repository: "ckan"
      command: "push"