apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: data-validation-cron
spec:
  schedule: "0 0 * * 0"
  failedJobsHistoryLimit: 10
  startingDeadlineSeconds: 600 # 10 min
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: <ACR_CREDENTIALS_SECRET_NAME>
          containers:
            - name: data-validation-cron
              image: <ACR_DOMAIN/IMAGE_REPO_NAME:LATEST_TAG>
              envFrom:
                - secretRef:
                    name: <CRONJOB_ENVVARS_SECRET_NAME>
              command: ["python"]
              args: ["./datachecker.py"]
              imagePullPolicy: Always
          restartPolicy: OnFailure